package:
    name: xwidgets
    version: 0.6.0
source:
    fn: xwidgets-0.6.0.tar.gz
    sha256: d791b6fb61332c5e5ab4928876d47921daad90a8b721935cad17c25d899fc2cb
    url: https://github.com/QuantStack/xwidgets/archive/0.6.0.tar.gz
build:
  noarch: ''
  noarch_python: false
  number: 0
  skip: true  # [win and py<35]
  features:   # [win]
    - vc14    # [win]

requirements:
  build:
    - toolchain
    - cmake
    - xeus >=0.9.0,<1.0
    - xtl >=0.3.8,<0.4.0
    - xproperty >=0.6.0,<0.7
  run:
    - xeus >=0.9.0,<1.0
    - cppzmq >=4.2.2,<4.3
    - xtl >=0.3.8,<0.4.0
    - xproperty >=0.6.0,<0.7
    
test:
  commands:
    - test -d ${PREFIX}/include/xwidgets  # [unix]
    - test -f ${PREFIX}/include/xwidgets/xtransport.hpp  # [unix]
    - test -f ${PREFIX}/lib/cmake/xwidgets/xwidgetsConfig.cmake  # [unix]
    - test -f ${PREFIX}/lib/cmake/xwidgets/xwidgetsConfigVersion.cmake  # [unix]
    - if exist %LIBRARY_PREFIX%\include\xwidgets\xtransport.hpp (exit 0) else (exit 1)  # [win]
    - if exist %LIBRARY_PREFIX%\lib\xwidgetsConfig.cmake (exit 0) else (exit 1)  # [win]
    - if exist %LIBRARY_PREFIX%\lib\xwidgetsConfigVersion.cmake (exit 0) else (exit 1)  # [win]

about:
  home: http://quantstack.net/xwidgets
  license: BSD 3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: 'C++ implementation of the Jupyter Interactive widgets'
  doc_url: http://xwidgets.readthedocs.io
  dev_url: https://github.com/QuantStack/xwidgets

extra:
  recipe-maintainers:
    - SylvainCorlay
    - JohanMabille
    - gouarin
