{% set name = "xwidgets" %}
{% set version = "0.7.0" %}
{% set sha256 = "565c37b73ddb17ca2b16fedf2b5407e9b26efeefc46758a532634d547af17372" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://github.com/QuantStack/xwidgets/archive/{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  noarch: ''
  noarch_python: false
  number: 1
  skip: true  # [win and py<35]
  features:
    - vc14    # [win]

requirements:
  build:
    - toolchain
    - cmake
    - xeus >=0.10.1,<0.11
    - xtl >=0.4,<0.5
    - xproperty >=0.7,<0.8
  run:
    - xeus >=0.10.1,<0.11
    - cppzmq 4.2.3
    - xtl >=0.4,<0.5
    - xproperty >=0.7,<0.8
    
test:
  commands:
    - test -d ${PREFIX}/include/xwidgets  # [unix]
    - test -f ${PREFIX}/include/xwidgets/xtransport.hpp  # [unix]
    - test -f ${PREFIX}/lib/cmake/xwidgets/xwidgetsConfig.cmake  # [unix]
    - test -f ${PREFIX}/lib/cmake/xwidgets/xwidgetsConfigVersion.cmake  # [unix]
    - if exist %LIBRARY_PREFIX%\include\xwidgets\xtransport.hpp (exit 0) else (exit 1)  # [win]
    - if exist %LIBRARY_PREFIX%\lib\xwidgetsConfig.cmake (exit 0) else (exit 1)  # [win]
    - if exist %LIBRARY_PREFIX%\lib\xwidgetsConfigVersion.cmake (exit 0) else (exit 1)  # [win]

about:
  home: http://quantstack.net/xwidgets
  license: BSD 3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: 'C++ implementation of the Jupyter Interactive widgets'
  doc_url: http://xwidgets.readthedocs.io
  dev_url: https://github.com/QuantStack/xwidgets

extra:
  recipe-maintainers:
    - SylvainCorlay
    - JohanMabille
    - gouarin
