language: generic
os: osx
osx_image: xcode6.4
env:
  matrix:
  - CONDA_PY=36
  global:
  - secure: Jxro2d/4WUSmjyh3JjYqi1TC6XC7ffbg6xc3+zZvMReBUegzO1inbJiSnuDV28qrF2wMAkc+OivfpYXl/iS8M3goGyWZ14d5SinfkjNOSOG1kRM+pKk4WCAcBmeSdAG0ah5G6i++C8ZHsCiimoiGq+q90cJyGiubKYxx+mXm6NvZR+XwTvRca8P97EScpXzP9B+wQ2RJdLkKcUZr5FbpTlFfAk7Tj/R2N0l88j/axYeuqtlcVK8jCSci52snm5i7xJd6Ysr8lmL0wreSjfE8huYM1XQqVx7Rp9MZPViDlbJjslexhUByF/DDC2tH17xfqgVx01zahxC/lnW4c2YyDHV0G8j8d/JwIZBUEpoj7M3+A4UKsG16eWpp6jvJFn/jbMTCq6gWgYLVIZqL/HDVcn9jufaYrRJNumNpYtOpReT5Sjr4mMLQwhE56Sh+uyh8UzBtASVLkGAHYz/9Sv/8AMC4oEXemsr5ec6D4H1pGWg8b66RRCwHJrsmzAaX3DJd3zyt9LP0qlSth953eMwgmtvmbWQCLp6sjw0N4eyxCvmGye2Axg+MvyhzIO1C8YjTlQMNtn0jUnUeicxF9C2dSq0Ee7HFj3q5mKUY999T1Q3jvRJRU/NQkbonfehumnxUgzvqfPlx+/5vIy8lYrYxsZMcCK/R+3tUB9JmGqMTJF8=
before_install:
- |
  (curl https://raw.githubusercontent.com/conda-forge/conda-forge-build-setup-feedstock/master/recipe/ff_ci_pr_build.py | \
      python - -v --ci "travis" "${TRAVIS_REPO_SLUG}" "${TRAVIS_BUILD_NUMBER}" "${TRAVIS_PULL_REQUEST}") || exit 1
- |
  echo ""
  echo "Removing homebrew from Travis CI to avoid conflicts."
  curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/uninstall > ~/uninstall_homebrew
  chmod +x ~/uninstall_homebrew
  ~/uninstall_homebrew -fq
  rm ~/uninstall_homebrew
install:
- |
  echo ""
  echo "Installing a fresh version of Miniconda."
  MINICONDA_URL="https://repo.continuum.io/miniconda"
  MINICONDA_FILE="Miniconda3-latest-MacOSX-x86_64.sh"
  curl -L -O "${MINICONDA_URL}/${MINICONDA_FILE}"
  bash $MINICONDA_FILE -b
- |
  echo ""
  echo "Configuring conda."
  source /Users/travis/miniconda3/bin/activate root
  conda config --remove channels defaults
  conda config --add channels defaults
  conda config --add channels conda-forge
  conda config --add channels QuantStack
  conda config --set show_channel_urls true
  conda install --yes --quiet conda-forge-build-setup
  source run_conda_forge_build_setup
script:
- conda build ./recipe
- upload_or_check_non_existence ./recipe QuantStack --channel=main
